export { IconlyProvider } from './lib/context'
export { useIconlyTheme } from './lib/context'
/** Icons  **/
export { default as Search } from './Icons/Search'
export { default as Folder } from './Icons/Folder'
export { default as Wallet } from './Icons/Wallet'
export { default as Graph } from './Icons/Graph'
export { default as Bookmark } from './Icons/Bookmark'
export { default as Category } from './Icons/Category'
export { default as Home } from './Icons/Home'
export { default as Notification } from './Icons/Notification'
export { default as Chat } from './Icons/Chat'
export { default as Heart } from './Icons/Heart'
export { default as Paper } from './Icons/Paper'
export { default as PaperPlus } from './Icons/PaperPlus'
export { default as PaperNegative } from './Icons/PaperNegative'
export { default as PaperFall } from './Icons/PaperFall'
export { default as PaperDownload } from './Icons/PaperDownload'
export { default as PaperUpload } from './Icons/PaperUpload'
export { default as Send } from './Icons/Send'
export { default as Password } from './Icons/Password'
export { default as Swap } from './Icons/Swap'
export { default as Work } from './Icons/Work'
export { default as Scan } from './Icons/Scan'
